CREATE OR REPLACE PACKAGE PKG_VALIDATIONS AS

    PROCEDURE VALIDATE_PHONE(P_PHONE IN VARCHAR2);

    PROCEDURE VALIDATE_EMAIL(P_EMAIL IN VARCHAR2);

    PROCEDURE VALIDATE_ROLE(P_EMP_ID IN NUMBER,P_DEA_ID IN NUMBER,P_ROLE IN VARCHAR2);

    PROCEDURE VALIDATE_STATE(P_STATE IN VARCHAR2);

    PROCEDURE VALIDATE_DATE(P_DATE IN DATE);

    PROCEDURE VALIDATE_NAME(P_NAME IN VARCHAR2);

    PROCEDURE VALIDATE_POSITIVE_NUMBER(P_VALUE IN NUMBER,P_FIELD IN VARCHAR2);

    PROCEDURE VALIDATE_LICENSE_PLATE(P_PLATE IN VARCHAR2);

    PROCEDURE VALIDATE_UNIT_CONDITION(P_CONDITION IN VARCHAR2);

    PROCEDURE VALIDATE_UNIT_STATUS(P_UNIT_STATUS IN VARCHAR2);

    PROCEDURE VALIDATE_SALE_STATUS(P_STATUS IN VARCHAR2);
    
    PROCEDURE VALIDATE_SALESGOAL_STATE(P_SGL_STATE IN VARCHAR2);

    PROCEDURE VALIDATE_GOAL_TYPE(P_GOAL_TYPE IN VARCHAR2);

    PROCEDURE VALIDATE_DATE_RANGE(P_START_DATE IN DATE,P_END_DATE   IN DATE);

    PROCEDURE VALIDATE_VEHICLE_FUEL_TYPE(P_FUEL_TYPE IN VARCHAR2);

    PROCEDURE VALIDATE_VEHICLE_CATEGORY(P_CATEGORY IN VARCHAR2);

END PKG_VALIDATIONS;
/

CREATE OR REPLACE PACKAGE BODY PKG_VALIDATIONS AS

    PROCEDURE VALIDATE_PHONE(P_PHONE IN VARCHAR2)
    IS
    BEGIN
        IF (P_PHONE IS NULL
           OR LENGTH(TRIM(P_PHONE)) != 10
           OR REGEXP_LIKE(P_PHONE, '[^0-9]'))
        THEN
            RAISE_APPLICATION_ERROR(-20001,'Telefono invalido. Debe contener exactamente 10 digitos.');
        END IF;

    END VALIDATE_PHONE;

    PROCEDURE VALIDATE_EMAIL(P_EMAIL IN VARCHAR2)
    IS
    BEGIN
        IF P_EMAIL IS NOT NULL THEN
            IF NOT REGEXP_LIKE(LOWER(TRIM(P_EMAIL)),'^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$') THEN
                RAISE_APPLICATION_ERROR(-20002,'Email invalido: ' || P_EMAIL);
            END IF;
        END IF;
    END VALIDATE_EMAIL;

    PROCEDURE VALIDATE_ROLE(P_EMP_ID IN NUMBER,P_DEA_ID IN NUMBER,P_ROLE   IN VARCHAR2)
    IS
        V_COUNT NUMBER;
    BEGIN

        IF (LOWER(TRIM(P_ROLE)) NOT IN ('manager', 'seller')) THEN
            RAISE_APPLICATION_ERROR(-20003,'Rol invalido. Debe ser manager o seller.');
        END IF;

        IF (LOWER(TRIM(P_ROLE)) = 'manager') THEN

            SELECT COUNT(*) INTO V_COUNT FROM TBL_EMPLOYEE 
            WHERE DEA_ID = P_DEA_ID AND LOWER(EMP_ROLE) = 'manager' AND EMP_ID <> P_EMP_ID;

            IF (V_COUNT > 0) THEN
                RAISE_APPLICATION_ERROR(-20017,'La concesionaria ya tiene un manager.');
            END IF;
        END IF;

    END VALIDATE_ROLE;

    PROCEDURE VALIDATE_STATE(P_STATE IN VARCHAR2)
    IS
    BEGIN
        IF (P_STATE IS NULL OR LENGTH(TRIM(P_STATE)) = 0) THEN
            RAISE_APPLICATION_ERROR(-20019,'Estado ingresado no valido');
        END IF;
        IF (LOWER(TRIM(P_STATE)) <> 'active') THEN
            RAISE_APPLICATION_ERROR(-20004,'El estado actual es inactive.');
        END IF;
    END VALIDATE_STATE;

    PROCEDURE VALIDATE_DATE(P_DATE IN DATE)
    IS
    BEGIN
        IF (P_DATE IS NULL OR P_DATE > SYSDATE) THEN
            RAISE_APPLICATION_ERROR(-20005,'La fecha ingresada es futura.');
        END IF;
    END VALIDATE_DATE;

    PROCEDURE VALIDATE_NAME(P_NAME IN VARCHAR2)
    IS
    BEGIN
        IF (P_NAME IS NULL OR LENGTH(TRIM(P_NAME)) = 0) THEN
            RAISE_APPLICATION_ERROR(-20006,'Nombre obligatorio.');
        END IF;
    END VALIDATE_NAME;

    PROCEDURE VALIDATE_POSITIVE_NUMBER(P_VALUE IN NUMBER,P_FIELD IN VARCHAR2)
    IS
    BEGIN
        IF (P_VALUE IS NULL OR P_VALUE < 0) THEN
            RAISE_APPLICATION_ERROR(-20007,P_FIELD || ' no puede ser nulo o negativo.');
        END IF;
    END VALIDATE_POSITIVE_NUMBER;

    PROCEDURE VALIDATE_LICENSE_PLATE(P_PLATE IN VARCHAR2)
    IS
    BEGIN
        IF (P_PLATE IS NULL OR NOT REGEXP_LIKE(UPPER(TRIM(P_PLATE)),'^[A-Z]{3}[0-9]{3}$')) THEN
            RAISE_APPLICATION_ERROR(-20008,'Placa invalida.');
        END IF;
    END VALIDATE_LICENSE_PLATE;

    PROCEDURE VALIDATE_UNIT_CONDITION(P_CONDITION IN VARCHAR2)
    IS
    BEGIN
        IF (P_CONDITION IS NULL OR LOWER(TRIM(P_CONDITION)) NOT IN ('new','used')) THEN
            RAISE_APPLICATION_ERROR(-20009,'Condicion invalida.');
        END IF;
    END VALIDATE_UNIT_CONDITION;
    
    PROCEDURE VALIDATE_UNIT_STATUS(P_UNIT_STATUS IN VARCHAR2)
    IS
    BEGIN
        IF(P_UNIT_STATUS IS NULL OR LENGTH(TRIM(P_UNIT_STATUS)) = 0)THEN
            RAISE_APPLICATION_ERROR(-20019,'Estado vacío o nulo');
        END IF;
        
        IF (LOWER(TRIM(P_UNIT_STATUS))NOT IN ('available', 'reserved', 'sold')) THEN
            RAISE_APPLICATION_ERROR(-20018,'Estado de unidad invalido.');
        END IF;
        
    END VALIDATE_UNIT_STATUS;

    PROCEDURE VALIDATE_SALE_STATUS(P_STATUS IN VARCHAR2)
    IS
    BEGIN
        IF(P_STATUS IS NULL OR LENGTH(TRIM(P_STATUS)) = 0)THEN
            RAISE_APPLICATION_ERROR(-20120,'Estado vacío o nulo');
        END IF;
        IF (LOWER(TRIM(P_STATUS))NOT IN ('confirmed','cancelled','inprogress')) THEN
            RAISE_APPLICATION_ERROR(-20010,'Estado de venta invalido.');
        END IF;
    END VALIDATE_SALE_STATUS;
   
    PROCEDURE VALIDATE_SALESGOAL_STATE(P_SGL_STATE IN VARCHAR2)
    IS
    BEGIN
        IF(P_SGL_STATE IS NULL OR LENGTH(TRIM(P_SGL_STATE)) = 0)THEN
            RAISE_APPLICATION_ERROR(-20121,'Estado vacío o nulo');
        END IF;
        IF(LOWER(TRIM(P_SGL_STATE))NOT IN ('inactive','active','complete'))THEN
            RAISE_APPLICATION_ERROR(-20022,'Estado de meta invalido.');
        END IF;
    END VALIDATE_SALESGOAL_STATE;

    PROCEDURE VALIDATE_GOAL_TYPE(P_GOAL_TYPE IN VARCHAR2)
    IS
    BEGIN
        IF (P_GOAL_TYPE IS NULL OR LENGTH(TRIM(P_GOAL_TYPE)) = 0) THEN 
            RAISE_APPLICATION_ERROR(-20020,'Tipo de meta vacío o nulo.');
        END IF;

        IF (LOWER(TRIM(P_GOAL_TYPE))NOT IN ('monthly','quarterly','yearly')) THEN
            RAISE_APPLICATION_ERROR(-20011,'Tipo de meta invalido.');
        END IF;
    END VALIDATE_GOAL_TYPE;

    PROCEDURE VALIDATE_DATE_RANGE(P_START_DATE IN DATE,P_END_DATE   IN DATE)
    IS
    BEGIN
        IF (P_END_DATE IS NOT NULL AND P_END_DATE < P_START_DATE) THEN
            RAISE_APPLICATION_ERROR(-20012,'La fecha final no puede ser menor a la inicial.');
        END IF;
    END VALIDATE_DATE_RANGE;

    PROCEDURE VALIDATE_VEHICLE_FUEL_TYPE(P_FUEL_TYPE IN VARCHAR2)
    IS
    BEGIN
        IF (P_FUEL_TYPE IS NULL OR LENGTH(TRIM(P_FUEL_TYPE)) = 0) THEN
            RAISE_APPLICATION_ERROR(-20013,'Tipo de combustible nulo o vacío.');
        END IF;

        IF (LOWER(p_FUEL_TYPE) NOT IN ('electric','gasoline','hybrid')) THEN
            RAISE_APPLICATION_ERROR(-20014,'Tipo de combustible no permitido.');
        END IF;

    END VALIDATE_VEHICLE_FUEL_TYPE;

    PROCEDURE VALIDATE_VEHICLE_CATEGORY(P_CATEGORY IN VARCHAR2)
    IS
    BEGIN
        IF (P_CATEGORY IS NULL OR LENGTH(TRIM(P_CATEGORY)) = 0) THEN
            RAISE_APPLICATION_ERROR(-20015,'Categoría nula o vacía.');
        END IF;
        IF (LOWER(TRIM(P_CATEGORY)) NOT IN ('standard','luxury')) THEN
            RAISE_APPLICATION_ERROR(-20016,'Categoría no permitida.');
        END IF;

    END VALIDATE_VEHICLE_CATEGORY;

END PKG_VALIDATIONS;
/