CREATE OR REPLACE PACKAGE PKG_VEHICLE AS

    PROCEDURE SP_REGISTER_VEHICLE(
        P_VEH_ID          IN TBL_VEHICLE.VEH_ID%TYPE,
        P_VEH_BRAND       IN TBL_VEHICLE.VEH_BRAND%TYPE,
        P_VEH_MODEL       IN TBL_VEHICLE.VEH_MODEL%TYPE,
        P_VEH_YEAR        IN TBL_VEHICLE.VEH_YEAR%TYPE,
        P_VEH_BODY_TYPE   IN TBL_VEHICLE.VEH_BODY_TYPE%TYPE,
        P_VEH_FUEL_TYPE   IN TBL_VEHICLE.VEH_FUEL_TYPE%TYPE,
        P_VEH_CATEGORY    IN TBL_VEHICLE.VEH_CATEGORY%TYPE
    );

    PROCEDURE SP_UPDATE_VEHICLE(
        P_VEH_ID          IN TBL_VEHICLE.VEH_ID%TYPE,
        P_VEH_BRAND       IN TBL_VEHICLE.VEH_BRAND%TYPE,
        P_VEH_MODEL       IN TBL_VEHICLE.VEH_MODEL%TYPE,
        P_VEH_YEAR        IN TBL_VEHICLE.VEH_YEAR%TYPE,
        P_VEH_BODY_TYPE   IN TBL_VEHICLE.VEH_BODY_TYPE%TYPE,
        P_VEH_FUEL_TYPE   IN TBL_VEHICLE.VEH_FUEL_TYPE%TYPE,
        P_VEH_CATEGORY    IN TBL_VEHICLE.VEH_CATEGORY%TYPE
    );

    PROCEDURE SP_DISABLE_VEHICLE(P_VEH_ID IN TBL_VEHICLE.VEH_ID%TYPE);
    
    FUNCTION FN_VEHICLE_EXIST(P_VEH_ID IN TBL_VEHICLE.VEH_ID%TYPE)
    RETURN BOOLEAN;

    FUNCTION FN_GET_VEHICLE_BY_ID(P_VEH_ID IN TBL_VEHICLE.VEH_ID%TYPE)
    RETURN TBL_VEHICLE%ROWTYPE;

    FUNCTION FN_GET_ALL_VEHICLES
    RETURN SYS_REFCURSOR;

END PKG_VEHICLE;
/

CREATE OR REPLACE PACKAGE BODY PKG_VEHICLE AS

    PROCEDURE SP_REGISTER_VEHICLE(
        P_VEH_ID          IN TBL_VEHICLE.VEH_ID%TYPE,
        P_VEH_BRAND       IN TBL_VEHICLE.VEH_BRAND%TYPE,
        P_VEH_MODEL       IN TBL_VEHICLE.VEH_MODEL%TYPE,
        P_VEH_YEAR        IN TBL_VEHICLE.VEH_YEAR%TYPE,
        P_VEH_BODY_TYPE   IN TBL_VEHICLE.VEH_BODY_TYPE%TYPE,
        P_VEH_FUEL_TYPE   IN TBL_VEHICLE.VEH_FUEL_TYPE%TYPE,
        P_VEH_CATEGORY    IN TBL_VEHICLE.VEH_CATEGORY%TYPE
    )
    IS
    BEGIN
        
        PKG_VALIDATIONS.VALIDATE_VEHICLE_CATEGORY(P_VEH_CATEGORY);
        PKG_VALIDATIONS.VALIDATE_VEHICLE_FUEL_TYPE(P_VEH_FUEL_TYPE);
        PKG_VALIDATIONS.VALIDATE_NAME(P_VEH_BODY_TYPE);
        PKG_VALIDATIONS.VALIDATE_NAME(P_VEH_MODEL);
        PKG_VALIDATIONS.VALIDATE_NAME(P_VEH_BRAND);
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_VEH_YEAR,'Year');
        
        IF (FN_VEHICLE_EXIST(P_VEH_ID)) THEN
            RAISE_APPLICATION_ERROR(-20403,'Vehiculo ya registrado.');
        END IF;
        IF (P_VEH_YEAR < 1886 OR P_VEH_YEAR > EXTRACT(YEAR FROM SYSDATE)+1) THEN
            RAISE_APPLICATION_ERROR(-20404,'El año del vehiculo es invalido');
        END IF;

        INSERT INTO TBL_VEHICLE(VEH_ID,VEH_BRAND,VEH_MODEL,VEH_YEAR,VEH_BODY_TYPE,VEH_FUEL_TYPE,VEH_CATEGORY,VEH_STATE)
        VALUES(P_VEH_ID,TRIM(P_VEH_BRAND),TRIM(P_VEH_MODEL),P_VEH_YEAR,TRIM(LOWER(P_VEH_BODY_TYPE)),
                TRIM(LOWER(P_VEH_FUEL_TYPE)),TRIM(LOWER(P_VEH_CATEGORY)),'active');

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');

    END SP_REGISTER_VEHICLE;

    PROCEDURE SP_UPDATE_VEHICLE(
        P_VEH_ID          IN TBL_VEHICLE.VEH_ID%TYPE,
        P_VEH_BRAND       IN TBL_VEHICLE.VEH_BRAND%TYPE,
        P_VEH_MODEL       IN TBL_VEHICLE.VEH_MODEL%TYPE,
        P_VEH_YEAR        IN TBL_VEHICLE.VEH_YEAR%TYPE,
        P_VEH_BODY_TYPE   IN TBL_VEHICLE.VEH_BODY_TYPE%TYPE,
        P_VEH_FUEL_TYPE   IN TBL_VEHICLE.VEH_FUEL_TYPE%TYPE,
        P_VEH_CATEGORY    IN TBL_VEHICLE.VEH_CATEGORY%TYPE
    )
    IS
        V_STATE TBL_VEHICLE.VEH_STATE%TYPE;
    BEGIN
    
        IF NOT(FN_VEHICLE_EXIST(P_VEH_ID)) THEN
            RAISE_APPLICATION_ERROR(-20403,'Vehiculo no encontrado.');
        END IF;
        
        PKG_VALIDATIONS.VALIDATE_VEHICLE_CATEGORY(P_VEH_CATEGORY);
        PKG_VALIDATIONS.VALIDATE_VEHICLE_FUEL_TYPE(P_VEH_FUEL_TYPE);
        PKG_VALIDATIONS.VALIDATE_NAME(P_VEH_BODY_TYPE);
        PKG_VALIDATIONS.VALIDATE_NAME(P_VEH_MODEL);
        PKG_VALIDATIONS.VALIDATE_NAME(P_VEH_BRAND);
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_VEH_YEAR,'Year');
        
        SELECT VEH_STATE INTO V_STATE FROM TBL_VEHICLE WHERE VEH_ID = P_VEH_ID;

        PKG_VALIDATIONS.VALIDATE_STATE(V_STATE);

        IF (P_VEH_YEAR < 1886 OR P_VEH_YEAR > EXTRACT(YEAR FROM SYSDATE)+1) THEN
            RAISE_APPLICATION_ERROR(-20404,'El año del vehiculo es invalido');
        END IF;

        UPDATE TBL_VEHICLE
        SET
            VEH_BRAND     = TRIM(P_VEH_BRAND),
            VEH_MODEL     = TRIM(P_VEH_MODEL),
            VEH_YEAR      = P_VEH_YEAR,
            VEH_BODY_TYPE = LOWER(P_VEH_BODY_TYPE), 
            VEH_FUEL_TYPE = LOWER(P_VEH_FUEL_TYPE),
            VEH_CATEGORY  = LOWER(P_VEH_CATEGORY)
        WHERE VEH_ID = P_VEH_ID;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20402,'Vehiculo no encontrado.');

    END SP_UPDATE_VEHICLE;

    PROCEDURE SP_DISABLE_VEHICLE(P_VEH_ID IN TBL_VEHICLE.VEH_ID%TYPE)
    IS
        V_UNITS NUMBER;
    BEGIN
        IF NOT(FN_VEHICLE_EXIST(P_VEH_ID)) THEN
            RAISE_APPLICATION_ERROR(-20403,'Vehiculo no encontrado.');
        END IF;

        SELECT COUNT(*) INTO V_UNITS FROM TBL_UNIT WHERE VEH_ID = P_VEH_ID AND UNIT_STATUS IN ('available','reserved');

        IF V_UNITS > 0 THEN
            RAISE_APPLICATION_ERROR(-20403,'Vehiculo con unidades activas.');
        END IF;

        UPDATE TBL_VEHICLE SET VEH_STATE = 'inactive' WHERE VEH_ID = P_VEH_ID;

    END SP_DISABLE_VEHICLE;

    FUNCTION FN_VEHICLE_EXIST(P_VEH_ID IN TBL_VEHICLE.VEH_ID%TYPE)
    RETURN BOOLEAN
    IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM TBL_VEHICLE WHERE VEH_ID = P_VEH_ID;
        
        RETURN V_COUNT > 0;
        
    END FN_VEHICLE_EXIST;

    FUNCTION FN_GET_VEHICLE_BY_ID(P_VEH_ID IN TBL_VEHICLE.VEH_ID%TYPE)
    RETURN TBL_VEHICLE%ROWTYPE
    IS
        V_VEHICLE TBL_VEHICLE%ROWTYPE;
    BEGIN

        IF NOT(FN_VEHICLE_EXIST(P_VEH_ID)) THEN
            RAISE_APPLICATION_ERROR(-20402,'Vehiculo no encontrado.');
        END IF;

        SELECT * INTO V_VEHICLE FROM TBL_VEHICLE
        WHERE VEH_ID = P_VEH_ID;

        RETURN V_VEHICLE;

    END FN_GET_VEHICLE_BY_ID;

    FUNCTION FN_GET_ALL_VEHICLES
    RETURN SYS_REFCURSOR
    IS
        V_CURSOR SYS_REFCURSOR;
    BEGIN

        OPEN V_CURSOR FOR
            SELECT * FROM TBL_VEHICLE
            ORDER BY VEH_BRAND, VEH_MODEL;

        RETURN V_CURSOR;
    END FN_GET_ALL_VEHICLES;

END PKG_VEHICLE;
/