CREATE OR REPLACE PACKAGE PKG_CUSTOMER AS

    PROCEDURE SP_REGISTER_CUSTOMER(
        P_CUS_ID      IN TBL_CUSTOMER.CUS_ID%TYPE,
        P_CUS_NAME    IN TBL_CUSTOMER.CUS_NAME%TYPE,
        P_CUS_PHONE   IN TBL_CUSTOMER.CUS_PHONE%TYPE,
        P_CUS_EMAIL   IN TBL_CUSTOMER.CUS_EMAIL%TYPE DEFAULT NULL
    );

    PROCEDURE SP_UPDATE_CUSTOMER(
        P_CUS_ID      IN TBL_CUSTOMER.CUS_ID%TYPE,
        P_CUS_NAME    IN TBL_CUSTOMER.CUS_NAME%TYPE DEFAULT NULL,
        P_CUS_PHONE   IN TBL_CUSTOMER.CUS_PHONE%TYPE DEFAULT NULL,
        P_CUS_EMAIL   IN TBL_CUSTOMER.CUS_EMAIL%TYPE DEFAULT NULL
    );

    PROCEDURE SP_DISABLE_CUSTOMER(P_CUS_ID IN TBL_CUSTOMER.CUS_ID%TYPE);
    
    FUNCTION FN_CUSTOMER_EXIST(P_CUS_ID IN TBL_CUSTOMER.CUS_ID%TYPE)
    RETURN BOOLEAN;

    FUNCTION FN_GET_CUSTOMER_BY_ID(P_CUS_ID IN TBL_CUSTOMER.CUS_ID%TYPE)
    RETURN TBL_CUSTOMER%ROWTYPE;

    FUNCTION FN_GET_ALL_CUSTOMERS
    RETURN SYS_REFCURSOR;

END PKG_CUSTOMER;
/

CREATE OR REPLACE PACKAGE BODY PKG_CUSTOMER AS

    PROCEDURE SP_REGISTER_CUSTOMER(
        P_CUS_ID      IN TBL_CUSTOMER.CUS_ID%TYPE,
        P_CUS_NAME    IN TBL_CUSTOMER.CUS_NAME%TYPE,
        P_CUS_PHONE   IN TBL_CUSTOMER.CUS_PHONE%TYPE,
        P_CUS_EMAIL   IN TBL_CUSTOMER.CUS_EMAIL%TYPE DEFAULT NULL
    )
    IS
    BEGIN
        IF (FN_CUSTOMER_EXIST(P_CUS_ID)) THEN
            RAISE_APPLICATION_ERROR(-20101,'Cliente ya existe.');
        END IF;
    
        PKG_VALIDATIONS.VALIDATE_NAME(P_CUS_NAME);
        PKG_VALIDATIONS.VALIDATE_PHONE(P_CUS_PHONE);
        PKG_VALIDATIONS.VALIDATE_EMAIL(P_CUS_EMAIL);
    
        INSERT INTO TBL_CUSTOMER (CUS_ID,CUS_NAME,CUS_PHONE,CUS_EMAIL,CUS_STATE)
        VALUES (P_CUS_ID,TRIM(P_CUS_NAME),P_CUS_PHONE,LOWER(P_CUS_EMAIL),'active');
    
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');
    
    END SP_REGISTER_CUSTOMER;

    PROCEDURE SP_UPDATE_CUSTOMER(
        P_CUS_ID      IN TBL_CUSTOMER.CUS_ID%TYPE,
        P_CUS_NAME    IN TBL_CUSTOMER.CUS_NAME%TYPE DEFAULT NULL,
        P_CUS_PHONE   IN TBL_CUSTOMER.CUS_PHONE%TYPE DEFAULT NULL,
        P_CUS_EMAIL   IN TBL_CUSTOMER.CUS_EMAIL%TYPE DEFAULT NULL) 
        
    IS
        V_STATE TBL_CUSTOMER.CUS_STATE%TYPE;
    BEGIN
        IF NOT(FN_CUSTOMER_EXIST(P_CUS_ID)) THEN
            RAISE_APPLICATION_ERROR(-20102,'Cliente no encontrado.');
        END IF;

        SELECT CUS_STATE INTO V_STATE FROM TBL_CUSTOMER WHERE CUS_ID = P_CUS_ID;

        PKG_VALIDATIONS.VALIDATE_STATE(V_STATE);

        IF P_CUS_PHONE IS NOT NULL THEN
            PKG_VALIDATIONS.VALIDATE_PHONE(P_CUS_PHONE);
        END IF;

        IF P_CUS_EMAIL IS NOT NULL THEN
            PKG_VALIDATIONS.VALIDATE_EMAIL(P_CUS_EMAIL);
        END IF;

        UPDATE TBL_CUSTOMER
        SET
            CUS_NAME  = TRIM(P_CUS_NAME),
            CUS_PHONE = P_CUS_PHONE,
            CUS_EMAIL = LOWER(P_CUS_EMAIL)
        WHERE CUS_ID = P_CUS_ID;

    END SP_UPDATE_CUSTOMER;

    PROCEDURE SP_DISABLE_CUSTOMER(P_CUS_ID IN TBL_CUSTOMER.CUS_ID%TYPE) 
    IS
        V_SALES NUMBER; 
    BEGIN

        SELECT COUNT(*) INTO V_SALES FROM TBL_SALE WHERE CUS_ID = P_CUS_ID AND SALE_STATUS = 'inprogress';

        IF (V_SALES > 0) THEN
            RAISE_APPLICATION_ERROR(-20103,'Cliente con ventas en progreso.');
        END IF;

        UPDATE TBL_CUSTOMER SET CUS_STATE = 'inactive' WHERE CUS_ID = P_CUS_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20102,'Cliente no encontrado.');
    END SP_DISABLE_CUSTOMER;

    FUNCTION FN_CUSTOMER_EXIST(P_CUS_ID IN TBL_CUSTOMER.CUS_ID%TYPE)
    RETURN BOOLEAN
    IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM TBL_CUSTOMER WHERE CUS_ID = P_CUS_ID;
        
        RETURN V_COUNT > 0;
        
    END FN_CUSTOMER_EXIST;

    FUNCTION FN_GET_CUSTOMER_BY_ID(P_CUS_ID IN TBL_CUSTOMER.CUS_ID%TYPE)
    RETURN TBL_CUSTOMER%ROWTYPE
    IS
        V_CUSTOMER TBL_CUSTOMER%ROWTYPE;
    BEGIN
        IF NOT(FN_CUSTOMER_EXIST(P_CUS_ID))THEN
            RAISE_APPLICATION_ERROR(-20102,'Cliente no encontrado.');
        END IF;
    
        SELECT * INTO V_CUSTOMER FROM TBL_CUSTOMER WHERE CUS_ID = P_CUS_ID;
    
        RETURN V_CUSTOMER;
    
    END FN_GET_CUSTOMER_BY_ID;
    
    FUNCTION FN_GET_ALL_CUSTOMERS
    RETURN SYS_REFCURSOR
    IS
        V_CURSOR SYS_REFCURSOR;
    BEGIN
        OPEN V_CURSOR FOR
            SELECT * FROM TBL_CUSTOMER
            ORDER BY CUS_NAME;
    
        RETURN V_CURSOR;
    
    END FN_GET_ALL_CUSTOMERS;
    
END PKG_CUSTOMER;
/