CREATE OR REPLACE PACKAGE PKG_DEALERSHIP AS

    PROCEDURE SP_REGISTER_DEALERSHIP(
        P_DEA_ID       IN TBL_DEALERSHIP.DEA_ID%TYPE,
        P_DEA_NAME     IN TBL_DEALERSHIP.DEA_NAME%TYPE,
        P_DEA_ADDRESS  IN TBL_DEALERSHIP.DEA_ADDRESS%TYPE,
        P_DEA_PHONE    IN TBL_DEALERSHIP.DEA_PHONE%TYPE
    );

    PROCEDURE SP_UPDATE_DEALERSHIP(
        P_DEA_ID       IN TBL_DEALERSHIP.DEA_ID%TYPE,
        P_DEA_NAME     IN TBL_DEALERSHIP.DEA_NAME%TYPE,
        P_DEA_ADDRESS  IN TBL_DEALERSHIP.DEA_ADDRESS%TYPE,
        P_DEA_PHONE    IN TBL_DEALERSHIP.DEA_PHONE%TYPE
    );

    PROCEDURE SP_DISABLE_DEALERSHIP(P_DEA_ID IN TBL_DEALERSHIP.DEA_ID%TYPE);
    
    FUNCTION FN_DEALERSHIP_EXIST(P_DEA_ID IN TBL_DEALERSHIP.DEA_ID%TYPE)
    RETURN BOOLEAN;

    FUNCTION FN_GET_DEALERSHIP_BY_ID(P_DEA_ID IN TBL_DEALERSHIP.DEA_ID%TYPE)
    RETURN TBL_DEALERSHIP%ROWTYPE;

    FUNCTION FN_GET_ALL_DEALERSHIPS
    RETURN SYS_REFCURSOR;

END PKG_DEALERSHIP;
/

CREATE OR REPLACE PACKAGE BODY PKG_DEALERSHIP AS

    PROCEDURE SP_REGISTER_DEALERSHIP(
        P_DEA_ID       IN TBL_DEALERSHIP.DEA_ID%TYPE,
        P_DEA_NAME     IN TBL_DEALERSHIP.DEA_NAME%TYPE,
        P_DEA_ADDRESS  IN TBL_DEALERSHIP.DEA_ADDRESS%TYPE,
        P_DEA_PHONE    IN TBL_DEALERSHIP.DEA_PHONE%TYPE
    )
    IS 
    BEGIN 
        PKG_VALIDATIONS.VALIDATE_NAME(P_DEA_NAME);
        PKG_VALIDATIONS.VALIDATE_PHONE(P_DEA_PHONE);
        
        IF (FN_DEALERSHIP_EXIST(P_DEA_ID)) THEN
            RAISE_APPLICATION_ERROR(-20201,'Concesionaria ya registrada.');
        END IF;
        
        INSERT INTO TBL_DEALERSHIP (DEA_ID,DEA_NAME,DEA_ADDRESS,DEA_PHONE,DEA_STATE)
        VALUES (P_DEA_ID,TRIM(P_DEA_NAME),P_DEA_ADDRESS,P_DEA_PHONE,'active');
        
        EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');
        
    END SP_REGISTER_DEALERSHIP;

    PROCEDURE SP_UPDATE_DEALERSHIP(
        P_DEA_ID       IN TBL_DEALERSHIP.DEA_ID%TYPE,
        P_DEA_NAME     IN TBL_DEALERSHIP.DEA_NAME%TYPE,
        P_DEA_ADDRESS  IN TBL_DEALERSHIP.DEA_ADDRESS%TYPE,
        P_DEA_PHONE    IN TBL_DEALERSHIP.DEA_PHONE%TYPE
    )
    IS
        V_STATE TBL_DEALERSHIP.DEA_STATE%TYPE;

    BEGIN
        IF NOT(FN_DEALERSHIP_EXIST(P_DEA_ID)) THEN
            RAISE_APPLICATION_ERROR(-20202,'Concesionaria no encontrada.');
        END IF;
        
        PKG_VALIDATIONS.VALIDATE_NAME(P_DEA_NAME);
        PKG_VALIDATIONS.VALIDATE_PHONE(P_DEA_PHONE);
        
        SELECT DEA_STATE INTO V_STATE FROM TBL_DEALERSHIP WHERE DEA_ID=P_DEA_ID;
        
        PKG_VALIDATIONS.VALIDATE_STATE(V_STATE);
        
        UPDATE TBL_DEALERSHIP
        SET
            DEA_NAME  = NVL(TRIM(P_DEA_NAME), DEA_NAME),
            DEA_PHONE = NVL(P_DEA_PHONE, DEA_PHONE),
            DEA_ADDRESS= NVL(P_DEA_ADDRESS, DEA_ADDRESS)
        WHERE DEA_ID = P_DEA_ID;
        
    END SP_UPDATE_DEALERSHIP;
    
    PROCEDURE SP_DISABLE_DEALERSHIP(P_DEA_ID IN TBL_DEALERSHIP.DEA_ID%TYPE)
    IS
    BEGIN
        IF NOT(FN_DEALERSHIP_EXIST(P_DEA_ID)) THEN
            RAISE_APPLICATION_ERROR(-20202,'Concesionaria no encontrada.');
        END IF;
        
        UPDATE TBL_DEALERSHIP SET DEA_STATE = 'inactive' WHERE DEA_ID = P_DEA_ID;
    END SP_DISABLE_DEALERSHIP;
  
    FUNCTION FN_DEALERSHIP_EXIST(P_DEA_ID IN TBL_DEALERSHIP.DEA_ID%TYPE)
    RETURN BOOLEAN
    IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM TBL_DEALERSHIP WHERE DEA_ID = P_DEA_ID;
        
        RETURN V_COUNT > 0;
        
    END FN_DEALERSHIP_EXIST;  
  
    FUNCTION FN_GET_DEALERSHIP_BY_ID(P_DEA_ID IN TBL_DEALERSHIP.DEA_ID%TYPE)
    RETURN TBL_DEALERSHIP%ROWTYPE
    IS
        V_DEALERSHIP TBL_DEALERSHIP%ROWTYPE;
    BEGIN
        IF NOT(FN_DEALERSHIP_EXIST(P_DEA_ID))THEN
            RAISE_APPLICATION_ERROR(-20202,'Concesionaria no encontrada');
        END IF;
        
        SELECT * INTO V_DEALERSHIP FROM TBL_DEALERSHIP 
        WHERE DEA_ID = P_DEA_ID;
        
        RETURN V_DEALERSHIP;
        
    END FN_GET_DEALERSHIP_BY_ID;
    
    FUNCTION FN_GET_ALL_DEALERSHIPS
    RETURN SYS_REFCURSOR
        IS
        V_CURSOR SYS_REFCURSOR;
    BEGIN
        OPEN V_CURSOR FOR
            SELECT * FROM TBL_DEALERSHIP
            ORDER BY DEA_NAME;

        RETURN V_CURSOR;
    END FN_GET_ALL_DEALERSHIPS;

END PKG_DEALERSHIP;
/