CREATE OR REPLACE PACKAGE PKG_UNIT AS

    PROCEDURE SP_REGISTER_UNIT(
        P_UNIT_ID             IN TBL_UNIT.UNIT_ID%TYPE,
        P_DEA_ID            IN TBL_UNIT.DEA_ID%TYPE,
        P_VEH_ID             IN TBL_UNIT.VEH_ID%TYPE,
        P_UNIT_LICENSE_PLATE  IN TBL_UNIT.UNIT_LICENSE_PLATE%TYPE,
        P_UNIT_COLOR          IN TBL_UNIT.UNIT_COLOR%TYPE,
        P_UNIT_MILEAGE        IN TBL_UNIT.UNIT_MILEAGE%TYPE,
        P_UNIT_DATE_ENTRY     IN TBL_UNIT.UNIT_DATE_ENTRY%TYPE,
        P_UNIT_CONDITION      IN TBL_UNIT.UNIT_CONDITION%TYPE
    );

    PROCEDURE SP_UPDATE_UNIT(
        P_UNIT_ID             IN TBL_UNIT.UNIT_ID%TYPE,
        P_UNIT_LICENSE_PLATE  IN TBL_UNIT.UNIT_LICENSE_PLATE%TYPE,
        P_UNIT_COLOR          IN TBL_UNIT.UNIT_COLOR%TYPE,
        P_UNIT_MILEAGE        IN TBL_UNIT.UNIT_MILEAGE%TYPE DEFAULT NULL,
        P_UNIT_CONDITION      IN TBL_UNIT.UNIT_CONDITION%TYPE
    );

    PROCEDURE SP_UPDATE_UNIT_STATUS(P_UNIT_ID IN TBL_UNIT.UNIT_ID%TYPE,P_UNIT_STATUS IN TBL_UNIT.UNIT_STATUS%TYPE);

    FUNCTION FN_UNIT_EXIST(P_UNIT_ID IN TBL_UNIT.UNIT_ID%TYPE)
    RETURN BOOLEAN;

    FUNCTION FN_GET_UNIT_BY_ID(P_UNIT_ID IN TBL_UNIT.UNIT_ID%TYPE)
    RETURN TBL_UNIT%ROWTYPE;

    FUNCTION FN_GET_ALL_UNITS
    RETURN SYS_REFCURSOR;

    FUNCTION FN_UNITS_BY_STATUS(P_UNIT_STATUS IN TBL_UNIT.UNIT_STATUS%TYPE)
    RETURN SYS_REFCURSOR;

END PKG_UNIT;
/

CREATE OR REPLACE PACKAGE BODY PKG_UNIT AS

    PROCEDURE SP_REGISTER_UNIT(
        P_UNIT_ID             IN TBL_UNIT.UNIT_ID%TYPE,
        P_DEA_ID            IN TBL_UNIT.DEA_ID%TYPE,
        P_VEH_ID             IN TBL_UNIT.VEH_ID%TYPE,
        P_UNIT_LICENSE_PLATE  IN TBL_UNIT.UNIT_LICENSE_PLATE%TYPE,
        P_UNIT_COLOR          IN TBL_UNIT.UNIT_COLOR%TYPE,
        P_UNIT_MILEAGE        IN TBL_UNIT.UNIT_MILEAGE%TYPE,
        P_UNIT_DATE_ENTRY     IN TBL_UNIT.UNIT_DATE_ENTRY%TYPE,
        P_UNIT_CONDITION      IN TBL_UNIT.UNIT_CONDITION%TYPE
    )
    IS
    BEGIN
        PKG_VALIDATIONS.VALIDATE_LICENSE_PLATE(P_UNIT_LICENSE_PLATE);
        PKG_VALIDATIONS.VALIDATE_UNIT_CONDITION(P_UNIT_CONDITION);
        PKG_VALIDATIONS.VALIDATE_DATE(P_UNIT_DATE_ENTRY);
        PKG_VALIDATIONS.VALIDATE_NAME(P_UNIT_COLOR);
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_UNIT_MILEAGE,'P_UNIT_MILEAGE');
        
        IF(FN_UNIT_EXIST(P_UNIT_ID))THEN
            RAISE_APPLICATION_ERROR(-20501,'La unidad ya está registrada');
        END IF;
        
        IF NOT(PKG_VEHICLE.FN_VEHICLE_EXIST(P_VEH_ID))THEN
            RAISE_APPLICATION_ERROR(-20506,'Línea de vehiculos no encontrada');
        END IF;
        
        IF NOT(PKG_DEALERSHIP.FN_DEALERSHIP_EXIST(P_DEA_ID))THEN
            RAISE_APPLICATION_ERROR(-20507,'Concesionaria no encontrada');
        END IF;
        
        INSERT INTO TBL_UNIT (UNIT_ID,DEA_ID,VEH_ID,UNIT_LICENSE_PLATE,UNIT_COLOR,UNIT_MILEAGE,UNIT_DATE_ENTRY,UNIT_CONDITION,UNIT_STATUS)
        VALUES (P_UNIT_ID,P_DEA_ID,P_VEH_ID,UPPER(TRIM(P_UNIT_LICENSE_PLATE)),LOWER(TRIM(P_UNIT_COLOR)),P_UNIT_MILEAGE,P_UNIT_DATE_ENTRY,LOWER(TRIM(P_UNIT_CONDITION)),'available');

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20900,'Violacion de PK o UNIQUE.');
        
    END SP_REGISTER_UNIT;

    PROCEDURE SP_UPDATE_UNIT(
        P_UNIT_ID             IN TBL_UNIT.UNIT_ID%TYPE,
        P_UNIT_LICENSE_PLATE  IN TBL_UNIT.UNIT_LICENSE_PLATE%TYPE,
        P_UNIT_COLOR          IN TBL_UNIT.UNIT_COLOR%TYPE,
        P_UNIT_MILEAGE        IN TBL_UNIT.UNIT_MILEAGE%TYPE DEFAULT NULL,
        P_UNIT_CONDITION      IN TBL_UNIT.UNIT_CONDITION%TYPE
    )
    IS
    BEGIN
    
        IF NOT(FN_UNIT_EXIST(P_UNIT_ID))THEN
            RAISE_APPLICATION_ERROR(-20502,'Unidad no encontrada');
        END IF;
        
        PKG_VALIDATIONS.VALIDATE_LICENSE_PLATE(P_UNIT_LICENSE_PLATE);
        PKG_VALIDATIONS.VALIDATE_UNIT_CONDITION(P_UNIT_CONDITION);
        PKG_VALIDATIONS.VALIDATE_POSITIVE_NUMBER(P_UNIT_MILEAGE,'P_UNIT_MILEAGE');
        
        UPDATE TBL_UNIT
        SET
            unit_license_plate = TRIM(UPPER(P_UNIT_LICENSE_PLATE)),
            unit_color = LOWER(TRIM(P_UNIT_COLOR)),
            unit_mileage = NVL(P_UNIT_MILEAGE, UNIT_MILEAGE),
            unit_condition = LOWER(TRIM(P_UNIT_CONDITION))
        WHERE UNIT_ID = P_UNIT_ID;
        
    END SP_UPDATE_UNIT;

    PROCEDURE SP_UPDATE_UNIT_STATUS(P_UNIT_ID IN TBL_UNIT.UNIT_ID%TYPE, P_UNIT_STATUS IN TBL_UNIT.UNIT_STATUS%TYPE)
    IS
        V_CURRENT_STATUS TBL_UNIT.UNIT_STATUS%TYPE;
    BEGIN
        IF NOT(FN_UNIT_EXIST(P_UNIT_ID))THEN
            RAISE_APPLICATION_ERROR(-20502,'Unidad no encotrada');
        END IF;
        
        PKG_VALIDATIONS.VALIDATE_UNIT_STATUS(P_UNIT_STATUS);
        
        SELECT UNIT_STATUS INTO V_CURRENT_STATUS FROM TBL_UNIT WHERE UNIT_ID = P_UNIT_ID;
        
        IF LOWER(TRIM(V_CURRENT_STATUS)) = 'sold' THEN
            RAISE_APPLICATION_ERROR(-20503, 'Una unidad vendida no puede cambiar de estado');
        END IF;
        
        IF LOWER(TRIM(V_CURRENT_STATUS)) = LOWER(TRIM(P_UNIT_STATUS)) THEN
            RAISE_APPLICATION_ERROR(-20508,'La unidad ya tiene ese estado');
        END IF;
            
            UPDATE TBL_UNIT SET UNIT_STATUS = LOWER(TRIM(P_UNIT_STATUS)) WHERE UNIT_ID = P_UNIT_ID;
    END SP_UPDATE_UNIT_STATUS;
    
    FUNCTION FN_UNIT_EXIST(P_UNIT_ID IN TBL_UNIT.UNIT_ID%TYPE)
    RETURN BOOLEAN
    IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM TBL_UNIT WHERE UNIT_ID = P_UNIT_ID;        
        RETURN V_COUNT > 0;

    END FN_UNIT_EXIST;
    
    FUNCTION FN_GET_UNIT_BY_ID(P_UNIT_ID IN TBL_UNIT.UNIT_ID%TYPE)
    RETURN TBL_UNIT%ROWTYPE
    IS
        V_UNIT TBL_UNIT%ROWTYPE;
    BEGIN
        
        IF NOT(FN_UNIT_EXIST(P_UNIT_ID))THEN
            RAISE_APPLICATION_ERROR(-20502,'Unidad no encotrada');
        END IF;
        
        SELECT * INTO V_UNIT FROM TBL_UNIT 
        WHERE UNIT_ID = P_UNIT_ID; 
        
        RETURN V_UNIT;
    END FN_GET_UNIT_BY_ID;

    FUNCTION FN_GET_ALL_UNITS
    RETURN SYS_REFCURSOR
    IS
    V_UNITS SYS_REFCURSOR;

    BEGIN

        OPEN V_UNITS FOR
        SELECT * FROM TBL_UNIT;

    RETURN V_UNITS;
    END FN_GET_ALL_UNITS;

    FUNCTION FN_UNITS_BY_STATUS(P_UNIT_STATUS IN TBL_UNIT.UNIT_STATUS%TYPE)
    RETURN SYS_REFCURSOR
    IS
    V_UNITS SYS_REFCURSOR;

    BEGIN
        PKG_VALIDATIONS.VALIDATE_UNIT_STATUS(P_UNIT_STATUS);
        
        OPEN V_UNITS FOR
        SELECT * FROM TBL_UNIT WHERE LOWER(TRIM(UNIT_STATUS))=LOWER(TRIM(P_UNIT_STATUS));

    RETURN V_UNITS;
    END FN_UNITS_BY_STATUS;

END PKG_UNIT;
/